# Generated by Django 5.0.6 on 2024-06-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200, null=True)),
                ('login_date', models.DateTimeField(verbose_name='date published')),
                ('login', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graf', models.ImageField(upload_to='static')),
                ('value', models.CharField(max_length=200)),
                ('user12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
