# Generated by Django 5.0.6 on 2024-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='graf',
            field=models.CharField(max_length=2000),
        ),
    ]
