# Generated by Django 5.0.6 on 2024-06-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_graf'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
