# Generated by Django 5.0.6 on 2024-06-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
