# Generated by Django 5.0.6 on 2024-07-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_id_alter_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='graf',
        ),
        migrations.AddField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
