# Generated by Django 5.0.6 on 2024-07-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('value', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('url', models.CharField(max_length=200, null=True)),
                ('user12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
