# Generated by Django 5.0.6 on 2024-07-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
