# Generated by Django 5.0.6 on 2024-07-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
