# Generated by Django 5.0.6 on 2024-07-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
