# Generated by Django 5.0.6 on 2024-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_question_id_alter_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
